# Generated by Django 5.2.1 on 2025-06-16 16:02

import academics.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='coursedocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Course Document', 'verbose_name_plural': 'Course Documents'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={'ordering': ['-enrolled_at']},
        ),
        migrations.AddField(
            model_name='coursedocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='coursedocument',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this document from students'),
        ),
        migrations.AlterField(
            model_name='coursedocument',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the document content', null=True),
        ),
        migrations.AlterField(
            model_name='coursedocument',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('doc', 'Word Document (.doc)'), ('docx', 'Word Document (.docx)'), ('xls', 'Excel Spreadsheet (.xls)'), ('xlsx', 'Excel Spreadsheet (.xlsx)'), ('ppt', 'PowerPoint Presentation (.ppt)'), ('pptx', 'PowerPoint Presentation (.pptx)'), ('txt', 'Text Document'), ('csv', 'CSV File'), ('zip', 'ZIP Archive'), ('rar', 'RAR Archive'), ('jpg', 'JPEG Image'), ('jpeg', 'JPEG Image'), ('png', 'PNG Image'), ('gif', 'GIF Image'), ('other', 'Other Format')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coursedocument',
            name='file',
            field=models.FileField(help_text='Supported formats: PDF, Word, Excel, PowerPoint, Text, CSV, ZIP, RAR, Images', upload_to=academics.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'zip', 'rar', 'jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='coursedocument',
            name='title',
            field=models.CharField(help_text='Enter a descriptive title for the document', max_length=255),
        ),
    ]
