# Generated by Django 5.2.1 on 2025-07-01 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a descriptive title for the note', max_length=255)),
                ('category', models.CharField(choices=[('lecture', 'Lecture Notes'), ('concept', 'Concept Explanation'), ('tutorial', 'Tutorial'), ('assignment', 'Assignment Guidelines'), ('exam_prep', 'Exam Preparation'), ('reference', 'Reference Material'), ('announcement', 'Course Announcement'), ('other', 'Other')], default='lecture', help_text='Categorize the type of note', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Difficulty level of the content', max_length=15)),
                ('content', models.TextField(help_text='Write your note content here')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g., python, loops, functions)', max_length=200, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured to highlight important notes')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this note from students')),
                ('chapter', models.CharField(blank=True, help_text='Chapter or section name (optional)', max_length=100, null=True)),
                ('estimated_read_time', models.PositiveIntegerField(blank=True, help_text='Estimated reading time in minutes', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Note',
                'verbose_name_plural': 'Course Notes',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['course', 'category'], name='academics_c_course__95ab2f_idx'), models.Index(fields=['course', 'is_featured'], name='academics_c_course__28863b_idx'), models.Index(fields=['course', 'order'], name='academics_c_course__5cf78b_idx')],
            },
        ),
    ]
